-- Migration 002: perluasan schema staging untuk Merit System Personel Polri.
-- Migration ini bersifat additive: tidak menghapus tabel atau data staging lama.
-- Jalankan pada database staging yang sama dengan sumber data kepegawaian.

BEGIN;

-- Satker menjadi scope organisasi yang dapat diberikan kepada operator.
CREATE TABLE IF NOT EXISTS satker (
    id_satker INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_satker VARCHAR(30) NOT NULL UNIQUE,
    nama_satker VARCHAR(150) NOT NULL,
    tipe_satker VARCHAR(20) NOT NULL CHECK (tipe_satker IN ('SSDM', 'POLDA', 'SATKER')),
    id_satker_induk INTEGER REFERENCES satker (id_satker),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Master fungsi, nivelering, dan status penugasan jabatan.
CREATE TABLE IF NOT EXISTS fungsi (
    id_fungsi INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_fungsi VARCHAR(30) NOT NULL UNIQUE,
    nama_fungsi VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS level_jabatan (
    id_level_jabatan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_level VARCHAR(30) NOT NULL UNIQUE,
    nama_level VARCHAR(100) NOT NULL,
    urutan SMALLINT NOT NULL CHECK (urutan > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS status_jabatan (
    id_status_jabatan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_status VARCHAR(30) NOT NULL UNIQUE,
    nama_status VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Menjamin tabel users tersedia baik pada schema backend maupun schema staging lama.
CREATE TABLE IF NOT EXISTS users (
    id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'viewer',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Relasi personel ke Satker untuk pembatasan data berbasis scope.
ALTER TABLE pegawai ADD COLUMN IF NOT EXISTS id_satker INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pegawai_id_satker_fkey') THEN
        ALTER TABLE pegawai ADD CONSTRAINT pegawai_id_satker_fkey
            FOREIGN KEY (id_satker) REFERENCES satker (id_satker);
    END IF;
END $$;

-- Histori jabatan: satu personel dapat memiliki banyak record sepanjang masa dinas.
CREATE TABLE IF NOT EXISTS riwayat_jabatan (
    id_riwayat_jabatan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pegawai INTEGER NOT NULL REFERENCES pegawai (id_pegawai) ON DELETE CASCADE,
    id_jabatan INTEGER NOT NULL REFERENCES jabatan (id_jabatan),
    id_satker INTEGER NOT NULL REFERENCES satker (id_satker),
    id_fungsi INTEGER REFERENCES fungsi (id_fungsi),
    id_level_jabatan INTEGER REFERENCES level_jabatan (id_level_jabatan),
    id_status_jabatan INTEGER NOT NULL REFERENCES status_jabatan (id_status_jabatan),
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE,
    keterangan TEXT,
    created_by INTEGER REFERENCES users (id_user),
    updated_by INTEGER REFERENCES users (id_user),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (tanggal_selesai IS NULL OR tanggal_selesai >= tanggal_mulai)
);

-- Satu personel tidak boleh memiliki dua histori aktif yang saling tumpang tindih.
CREATE UNIQUE INDEX IF NOT EXISTS uq_riwayat_jabatan_aktif
    ON riwayat_jabatan (id_pegawai)
    WHERE tanggal_selesai IS NULL;
CREATE INDEX IF NOT EXISTS ix_riwayat_jabatan_pegawai_waktu
    ON riwayat_jabatan (id_pegawai, tanggal_mulai DESC);
CREATE INDEX IF NOT EXISTS ix_riwayat_jabatan_satker
    ON riwayat_jabatan (id_satker);
CREATE INDEX IF NOT EXISTS ix_pegawai_satker
    ON pegawai (id_satker);

-- Scope user: Admin SSDM dapat melihat semua scope; operator diberi satu/lebih scope.
CREATE TABLE IF NOT EXISTS user_scope (
    id_user INTEGER NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    id_satker INTEGER NOT NULL REFERENCES satker (id_satker) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_user, id_satker)
);

-- Audit minimum untuk perubahan data personel dan histori jabatan.
CREATE TABLE IF NOT EXISTS audit_log (
    id_audit BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER REFERENCES users (id_user),
    action VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'READ', 'UPDATE', 'DELETE')),
    resource VARCHAR(80) NOT NULL,
    resource_id VARCHAR(80),
    request_id VARCHAR(100),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Area staging tetap dipertahankan untuk validasi sebelum data dipromosikan ke tabel utama.
CREATE TABLE IF NOT EXISTS staging_pegawai (
    nip VARCHAR(30),
    nik VARCHAR(30),
    nama VARCHAR(150),
    tanggal_lahir VARCHAR(30),
    tanggal_masuk VARCHAR(30),
    kode_unit VARCHAR(30),
    golongan VARCHAR(10),
    kode_satker VARCHAR(30),
    status_validasi VARCHAR(30) NOT NULL DEFAULT 'BELUM_DIVALIDASI',
    masalah JSONB NOT NULL DEFAULT '[]'::jsonb,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE staging_pegawai ADD COLUMN IF NOT EXISTS kode_satker VARCHAR(30);
ALTER TABLE staging_pegawai ADD COLUMN IF NOT EXISTS status_validasi VARCHAR(30) NOT NULL DEFAULT 'BELUM_DIVALIDASI';
ALTER TABLE staging_pegawai ADD COLUMN IF NOT EXISTS masalah JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE staging_pegawai ADD COLUMN IF NOT EXISTS loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE INDEX IF NOT EXISTS ix_staging_pegawai_status
    ON staging_pegawai (status_validasi);

COMMIT;
