-- Migration 011: tahap 1 hierarki SOTK untuk 20 Satker Mabes yang dipakai aplikasi.
-- Sumber struktur: Perkap No. 6 Tahun 2017 dan perubahan-perubahannya.
-- Tahap ini mengisi unsur/Biro/Bagian tingkat pertama yang telah terverifikasi.
-- Level Subbagian/Urusan/Unit diisi bertahap dari lampiran SOTK masing-masing.
BEGIN;

ALTER TABLE unit_kerja ADD COLUMN IF NOT EXISTS sumber_sotk VARCHAR(160);
ALTER TABLE unit_kerja ADD COLUMN IF NOT EXISTS versi_sotk VARCHAR(40);
ALTER TABLE unit_kerja ADD COLUMN IF NOT EXISTS is_placeholder BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE unit_kerja u
SET is_placeholder=TRUE, sumber_sotk='Placeholder sebelum pemetaan SOTK', versi_sotk='legacy'
FROM satker s
WHERE u.id_satker=s.id_satker AND s.tipe_satker='SATKER_MABES' AND u.kode_unit='SATKER_UTAMA';

WITH nodes(satker_code, kode, nama, tipe, urutan) AS (VALUES
 ('BAINTELKAM','RORENMIN','Biro Perencanaan dan Administrasi','BIRO',10),('BAINTELKAM','ROANALIS','Biro Analisis','BIRO',20),('BAINTELKAM','URKEU','Urusan Keuangan','URUSAN',30),('BAINTELKAM','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',40),('BAINTELKAM','BIDSANDI','Bidang Sandi','BIDANG',50),('BAINTELKAM','BIDINTELTEK','Bidang Intelijen dan Teknologi','BIDANG',60),('BAINTELKAM','BIDYANMAS','Bidang Pelayanan Masyarakat','BIDANG',70),('BAINTELKAM','BIDKERMA','Bidang Kerja Sama','BIDANG',80),('BAINTELKAM','DITPOLITIK','Direktorat Politik','DIREKTORAT',90),('BAINTELKAM','DITEKONOMI','Direktorat Ekonomi','DIREKTORAT',100),('BAINTELKAM','DITSOSBUD','Direktorat Sosial Budaya','DIREKTORAT',110),('BAINTELKAM','DITKAMNEG','Direktorat Keamanan Negara','DIREKTORAT',120),('BAINTELKAM','DITKAMSUS','Direktorat Keamanan Khusus','DIREKTORAT',130),
 ('BAHARKAM','RORENMIN','Biro Perencanaan dan Administrasi','BIRO',10),('BAHARKAM','ROBINOPSNAL','Biro Pembinaan Operasional','BIRO',20),('BAHARKAM','URKEU','Urusan Keuangan','URUSAN',30),('BAHARKAM','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',40),('BAHARKAM','KORBINMAS','Korps Pembinaan Masyarakat','KORPS',50),('BAHARKAM','DITBINTIBMAS','Direktorat Pembinaan Penertiban Masyarakat','DIREKTORAT',60),('BAHARKAM','DITBINPOTMAS','Direktorat Pembinaan Potensi Masyarakat','DIREKTORAT',70),
 ('BARESKRIM','RORENMIN','Biro Perencanaan dan Administrasi','BIRO',10),('BARESKRIM','ROBINOPSNAL','Biro Pembinaan Operasional','BIRO',20),('BARESKRIM','ROWASSIDIK','Biro Pengawas Penyidikan','BIRO',30),('BARESKRIM','ROKORWAS_PPNS','Biro Koordinasi dan Pengawasan PPNS','BIRO',40),('BARESKRIM','URKEU','Urusan Keuangan','URUSAN',50),('BARESKRIM','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',60),('BARESKRIM','PUSIKNAS','Pusat Informasi Kriminal Nasional','PUSAT',70),('BARESKRIM','PUSIDENT','Pusat Indonesian Automatic Fingerprint Identification System','PUSAT',80),('BARESKRIM','PUSLABFOR','Pusat Laboratorium Forensik','PUSAT',90),('BARESKRIM','DITTIPIDUM','Direktorat Tindak Pidana Umum','DIREKTORAT',100),('BARESKRIM','DITTIPIDEKSUS','Direktorat Tindak Pidana Ekonomi Khusus','DIREKTORAT',110),('BARESKRIM','DITTIPIDNARKOBA','Direktorat Tindak Pidana Narkoba','DIREKTORAT',120),('BARESKRIM','DITTIPIDTER','Direktorat Tindak Pidana Tertentu','DIREKTORAT',130),('BARESKRIM','DITTIPIDSIBER','Direktorat Tindak Pidana Siber','DIREKTORAT',140),
 ('ITWASUM','RORENMIN','Biro Perencanaan Administrasi','BIRO',10),('ITWASUM','URKEU','Urusan Keuangan','URUSAN',20),('ITWASUM','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',30),('ITWASUM','ITWIL_1','Inspektorat Wilayah I','INSPEKTORAT',40),('ITWASUM','ITWIL_2','Inspektorat Wilayah II','INSPEKTORAT',50),('ITWASUM','ITWIL_3','Inspektorat Wilayah III','INSPEKTORAT',60),('ITWASUM','ITWIL_4','Inspektorat Wilayah IV','INSPEKTORAT',70),('ITWASUM','ITWIL_5','Inspektorat Wilayah V','INSPEKTORAT',80),
 ('SOPS','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('SOPS','URKEU','Urusan Keuangan','URUSAN',20),('SOPS','ROJIANSTRA','Biro Pengkajian dan Strategi','BIRO',30),('SOPS','ROBINOPS','Biro Pembinaan Operasi','BIRO',40),('SOPS','ROKERMA_KL','Biro Kerja Sama Kementerian/Lembaga','BIRO',50),('SOPS','RODALOPS','Biro Pengendalian Operasi','BIRO',60),
 ('SSDM','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('SSDM','URKEU','Urusan Keuangan','URUSAN',20),('SSDM','ROJIANSTRA','Biro Pengkajian dan Strategi','BIRO',30),('SSDM','RODALPERS','Biro Pengendalian Personel','BIRO',40),('SSDM','ROBINKAR','Biro Pembinaan Karier','BIRO',50),('SSDM','ROWATPERS','Biro Perawatan Personel','BIRO',60),('SSDM','ROPSI','Biro Psikologi','BIRO',70),
 ('SLOG','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('SLOG','URKEU','Urusan Keuangan','URUSAN',20),('SLOG','ROJIANSTRA','Biro Pengkajian dan Strategi','BIRO',30),('SLOG','ROBEKUM','Biro Perbekalan Umum','BIRO',40),('SLOG','ROPAL','Biro Peralatan','BIRO',50),('SLOG','ROFASKON','Biro Fasilitas dan Konstruksi','BIRO',60),('SLOG','DOMAT','Depo Materiil','DEPO',70),
 ('DIVPROPAM','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('DIVPROPAM','BAGYANDUAN','Bagian Pelayanan dan Pengaduan','BAGIAN',20),('DIVPROPAM','BAGREHABPERS','Bagian Rehabilitasi Personel','BAGIAN',30),('DIVPROPAM','URKEU','Urusan Keuangan','URUSAN',40),('DIVPROPAM','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',50),('DIVPROPAM','ROPAMINAL','Biro Pengamanan Internal','BIRO',60),('DIVPROPAM','ROPROVOS','Biro Provos','BIRO',70),('DIVPROPAM','ROWABPROF','Biro Pertanggungjawaban Profesi','BIRO',80),
 ('DIVKUM','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('DIVKUM','URKEU','Urusan Keuangan','URUSAN',20),('DIVKUM','ROPENYULUHAN','Biro Penyusunan dan Penyuluhan Hukum','BIRO',30),('DIVKUM','ROBANKUM','Biro Bantuan Hukum','BIRO',40),
 ('DIVHUMAS','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('DIVHUMAS','URKEU','Urusan Keuangan','URUSAN',20),('DIVHUMAS','ROPENMAS','Biro Penerangan Masyarakat','BIRO',30),('DIVHUMAS','ROPID','Biro Pengelolaan Informasi dan Dokumentasi','BIRO',40),('DIVHUMAS','ROMULMED','Biro Multimedia','BIRO',50),
 ('DIVHUBINTER','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('DIVHUBINTER','BAGPROT','Bagian Protokol','BAGIAN',20),('DIVHUBINTER','URKEU','Urusan Keuangan','URUSAN',30),('DIVHUBINTER','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',40),('DIVHUBINTER','SET_NCB','Sekretariat NCB Interpol Indonesia','SEKRETARIAT',50),('DIVHUBINTER','ROMISINTER','Biro Misi Internasional','BIRO',60),
 ('DIVTIK','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',10),('DIVTIK','BAGJEMEN_TIK','Bagian Manajemen Teknologi Informasi dan Komunikasi','BAGIAN',20),('DIVTIK','URKEU','Urusan Keuangan','URUSAN',30),('DIVTIK','ROTEKKOM','Biro Teknologi Komunikasi','BIRO',40),('DIVTIK','ROTEKINFO','Biro Teknologi Informasi','BIRO',50),('DIVTIK','DEPOHARKAN','Depo Pemeliharaan dan Perbaikan','DEPO',60),
 ('BRIMOB','BAGREN','Bagian Perencanaan','BAGIAN',10),('BRIMOB','BAGOPS','Bagian Operasi','BAGIAN',20),('BRIMOB','BAGSDM','Bagian Sumber Daya Manusia','BAGIAN',30),('BRIMOB','BAGLOG','Bagian Logistik','BAGIAN',40),('BRIMOB','SIKEU','Seksi Keuangan','SEKSI',50),('BRIMOB','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',60),('BRIMOB','BIDPROPAM','Bidang Profesi dan Pengamanan','BIDANG',70),('BRIMOB','BIDKESJAS','Bidang Kesehatan dan Jasmani','BIDANG',80),('BRIMOB','BIDTIK','Bidang Teknologi Informasi dan Komunikasi','BIDANG',90),('BRIMOB','DENMA','Detasemen Markas','DETASEMEN',100),('BRIMOB','PASGEGANA','Pasukan Gegana','PASUKAN',110),('BRIMOB','PASPELOPOR','Pasukan Pelopor','PASUKAN',120),('BRIMOB','SATLAT_BRIMOB','Satuan Latihan Brimob','SATUAN',130),('BRIMOB','SATINTEL_BRIMOB','Satuan Intelijen Brimob','SATUAN',140),
 ('DENSUS88','BAGOPS','Bagian Operasional','BAGIAN',10),('DENSUS88','BAGBANOPS','Bagian Bantuan Operasional','BAGIAN',20),('DENSUS88','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',30),('DENSUS88','URKEU','Urusan Keuangan','URUSAN',40),('DENSUS88','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',50),('DENSUS88','DITINTEL','Direktorat Intelijen','DIREKTORAT',60),
 ('KORLANTAS','BAGOPS','Bagian Operasional','BAGIAN',10),('KORLANTAS','BAGTIK','Bagian Teknologi Informasi dan Komunikasi','BAGIAN',20),('KORLANTAS','BAGRENMIN','Bagian Perencanaan dan Administrasi','BAGIAN',30),('KORLANTAS','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',40),('KORLANTAS','SIKEU','Seksi Keuangan','SEKSI',50),('KORLANTAS','DITKAMSEL','Direktorat Keamanan dan Keselamatan','DIREKTORAT',60),('KORLANTAS','DITGAKKUM','Direktorat Penegakan Hukum','DIREKTORAT',70),('KORLANTAS','DITREGIDENT','Direktorat Registrasi dan Identifikasi','DIREKTORAT',80)
), targets AS (SELECT id_satker,kode_satker FROM satker WHERE tipe_satker='SATKER_MABES')
INSERT INTO unit_kerja (id_unit,kode_unit,nama_unit,id_satker,tipe_unit,sumber_sotk,versi_sotk,is_placeholder,is_active)
SELECT COALESCE((SELECT MAX(id_unit) FROM unit_kerja),0)+ROW_NUMBER() OVER (ORDER BY t.id_satker,n.urutan), n.kode,n.nama,t.id_satker,n.tipe,'Perkap No. 6 Tahun 2017','2017',FALSE,TRUE
FROM targets t JOIN nodes n ON n.satker_code=t.kode_satker
ON CONFLICT (id_satker,kode_unit) DO UPDATE SET nama_unit=EXCLUDED.nama_unit,tipe_unit=EXCLUDED.tipe_unit,sumber_sotk=EXCLUDED.sumber_sotk,versi_sotk=EXCLUDED.versi_sotk,is_placeholder=FALSE,is_active=TRUE;

INSERT INTO fungsi (kode_fungsi,nama_fungsi,is_active)
SELECT 'SATFUNG_'||kode_unit,MIN(nama_unit),TRUE FROM unit_kerja WHERE id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT is_placeholder GROUP BY kode_unit
ON CONFLICT (kode_fungsi) DO UPDATE SET nama_fungsi=EXCLUDED.nama_fungsi,is_active=TRUE;
INSERT INTO satker_fungsi (id_satker,id_fungsi,is_active)
SELECT u.id_satker,f.id_fungsi,TRUE FROM unit_kerja u JOIN fungsi f ON f.kode_fungsi='SATFUNG_'||u.kode_unit WHERE u.id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT u.is_placeholder
ON CONFLICT (id_satker,id_fungsi) DO UPDATE SET is_active=TRUE,updated_at=NOW();
COMMIT;
