-- Migration 012: unsur tingkat pertama Satker Mabes pendukung yang tersisa.
-- Sumber: Perkap No. 6 Tahun 2017 Pasal 28-32.
BEGIN;
WITH nodes(satker_code,kode,nama,tipe,urutan) AS (VALUES
 ('LEMDIKLAT','LSP','Lembaga Sertifikasi Profesi','LEMBAGA',10),('LEMDIKLAT','URKEU','Urusan Keuangan','URUSAN',20),('LEMDIKLAT','TAUD','Tata Usaha dan Urusan Dalam','URUSAN',30),('LEMDIKLAT','RORENMIN','Biro Perencanaan dan Administrasi','BIRO',40),('LEMDIKLAT','ROJIANBANG','Biro Pengkajian dan Pengembangan','BIRO',50),('LEMDIKLAT','ROBINDIKLAT','Biro Pembinaan Pendidikan dan Pelatihan','BIRO',60),('LEMDIKLAT','ROKURLUM','Biro Kurikulum','BIRO',70),('LEMDIKLAT','SESPIM','Sekolah Staf dan Pimpinan','SEKOLAH',80),('LEMDIKLAT','STIK','Sekolah Tinggi Ilmu Kepolisian','SEKOLAH',90),('LEMDIKLAT','AKPOL','Akademi Kepolisian','SEKOLAH',100),('LEMDIKLAT','SETUKPA','Sekolah Pembentukan Perwira','SEKOLAH',110),('LEMDIKLAT','PUSDIK','Pusat Pendidikan/Sekolah','PUSAT',120),
 ('PUSDOKKES','SET','Sekretariat','SEKRETARIAT',10),('PUSDOKKES','URKEU','Urusan Keuangan','URUSAN',20),('PUSDOKKES','BIDDOKPOL','Bidang Kedokteran Kepolisian','BIDANG',30),('PUSDOKKES','BID_DVI','Bidang Identifikasi Korban Bencana/DVI','BIDANG',40),('PUSDOKKES','BIDYANKES','Bidang Pelayanan Kesehatan','BIDANG',50),('PUSDOKKES','BIDKESMAPTA','Bidang Kesamaptaan','BIDANG',60),('PUSDOKKES','BAGOPSNALMED','Bagian Operasional Medikal','BAGIAN',70),('PUSDOKKES','BAGFARMAPOL','Bagian Farmalogi Kepolisian','BAGIAN',80),('PUSDOKKES','BAGMATFASKES','Bagian Material dan Fasilitas Kesehatan','BAGIAN',90),('PUSDOKKES','LKOK','Laboratorium dan Klinik Odontologi Kepolisian','LABORATORIUM',100),('PUSDOKKES','LAB_DNA','Laboratorium DNA','LABORATORIUM',110),('PUSDOKKES','RUMKIT','Rumah Sakit Bhayangkara Tingkat I','RUMAH_SAKIT',120),('PUSDOKKES','SATKES','Satuan Kesehatan','SATUAN',130),
 ('PUSKEU','SET','Sekretariat','SEKRETARIAT',10),('PUSKEU','URKEU','Urusan Keuangan','URUSAN',20),('PUSKEU','BIDBIA','Bidang Pembiayaan','BIDANG',30),('PUSKEU','BIDAPK','Bidang Akuntansi Pelaporan Keuangan','BIDANG',40),('PUSKEU','BIDDAL','Bidang Pengendalian','BIDANG',50),('PUSKEU','BIDVERIF','Bidang Verifikasi','BIDANG',60),('PUSKEU','BIDKU_MABES','Bidang Keuangan Mabes','BIDANG',70),
 ('PUSINAFIS','SET','Sekretariat','SEKRETARIAT',10),('PUSINAFIS','BAGSISINFO','Bagian Sistem Informasi','BAGIAN',20),('PUSINAFIS','BIDDAKTIUM','Bidang Daktiloskopi Umum','BIDANG',30),('PUSINAFIS','BIDDAKTIKRIM','Bidang Daktiloskopi Kriminal','BIDANG',40),('PUSINAFIS','BIDTOPOL','Bidang Fotografi Kepolisian','BIDANG',50),
 ('PUSLABFOR','SET','Sekretariat','SEKRETARIAT',10),('PUSLABFOR','BAGJEMENMUT','Bagian Manajemen Mutu','BAGIAN',20),('PUSLABFOR','URKEU','Urusan Keuangan','URUSAN',30),('PUSLABFOR','BIDDOKUPALFOR','Bidang Dokumen dan Uang Palsu Forensik','BIDANG',40),('PUSLABFOR','BIDBALMETFOR','Bidang Balistik Metalurgi Forensik','BIDANG',50),('PUSLABFOR','BIDFISKOMFOR','Bidang Fisika Komputer Forensik','BIDANG',60),('PUSLABFOR','BIDKIMBIOFOR','Bidang Kimia Biologi Forensik','BIDANG',70),('PUSLABFOR','BIDNARKOBAFOR','Bidang Narkoba Forensik','BIDANG',80),('PUSLABFOR','LABFORCAB','Laboratorium Forensik Cabang','LABORATORIUM',90)
), targets AS (SELECT id_satker,kode_satker FROM satker WHERE tipe_satker='SATKER_MABES')
INSERT INTO unit_kerja(id_unit,kode_unit,nama_unit,id_satker,tipe_unit,sumber_sotk,versi_sotk,is_placeholder,is_active)
SELECT COALESCE((SELECT MAX(id_unit) FROM unit_kerja)+ROW_NUMBER() OVER (ORDER BY t.id_satker,n.urutan),0),n.kode,n.nama,t.id_satker,n.tipe,'Perkap No. 6 Tahun 2017','2017',FALSE,TRUE
FROM targets t JOIN nodes n ON n.satker_code=t.kode_satker
ON CONFLICT(id_satker,kode_unit) DO UPDATE SET nama_unit=EXCLUDED.nama_unit,tipe_unit=EXCLUDED.tipe_unit,sumber_sotk=EXCLUDED.sumber_sotk,versi_sotk=EXCLUDED.versi_sotk,is_placeholder=FALSE,is_active=TRUE;
INSERT INTO fungsi(kode_fungsi,nama_fungsi,is_active)
SELECT 'SATFUNG_'||kode_unit,MIN(nama_unit),TRUE FROM unit_kerja WHERE id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT is_placeholder GROUP BY kode_unit
ON CONFLICT(kode_fungsi) DO UPDATE SET nama_fungsi=EXCLUDED.nama_fungsi,is_active=TRUE;
INSERT INTO satker_fungsi(id_satker,id_fungsi,is_active)
SELECT u.id_satker,f.id_fungsi,TRUE FROM unit_kerja u JOIN fungsi f ON f.kode_fungsi='SATFUNG_'||u.kode_unit WHERE u.id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT u.is_placeholder
ON CONFLICT(id_satker,id_fungsi) DO UPDATE SET is_active=TRUE,updated_at=NOW();
COMMIT;
