-- Migration 013: child level terverifikasi Bareskrim dan Itwasum.
-- Sumber: Perkap No. 6 Tahun 2017 Pasal 6 dan Pasal 23, jo. Perpol No. 4 Tahun 2025.
BEGIN;
WITH nodes(satker_code,parent_code,kode,nama,tipe,urutan) AS (VALUES
 ('BARESKRIM','RORENMIN','BAGREN','Bagian Perencanaan','BAGIAN',10),('BARESKRIM','RORENMIN','BAGBINFUNG','Bagian Pembinaan Fungsi','BAGIAN',20),('BARESKRIM','RORENMIN','BAGSUMDA','Bagian Sumber Daya','BAGIAN',30),('BARESKRIM','RORENMIN','BAGTAHTI','Bagian Perawatan Tahanan dan Barang Bukti','BAGIAN',40),('BARESKRIM','RORENMIN','URTU','Urusan Tata Usaha','URUSAN',50),
 ('BARESKRIM','ROBINOPSNAL','BAGRENOPSNAL','Bagian Perencanaan Operasional','BAGIAN',10),('BARESKRIM','ROBINOPSNAL','BAGKERMA','Bagian Kerja Sama','BAGIAN',20),('BARESKRIM','ROBINOPSNAL','BAGANEV','Bagian Analisis dan Evaluasi','BAGIAN',30),('BARESKRIM','ROBINOPSNAL','BAGMON','Bagian Monitoring','BAGIAN',40),('BARESKRIM','ROBINOPSNAL','BAGYANMAS','Bagian Pelayanan Masyarakat','BAGIAN',50),('BARESKRIM','ROBINOPSNAL','URTU','Urusan Tata Usaha','URUSAN',60),
 ('BARESKRIM','ROWASSIDIK','BAGMINDIK','Bagian Administrasi Penyidikan','BAGIAN',10),('BARESKRIM','ROWASSIDIK','BAGVISILAP','Bagian Supervisi dan Pelaporan','BAGIAN',20),('BARESKRIM','ROWASSIDIK','URTU','Urusan Tata Usaha','URUSAN',30),
 ('BARESKRIM','ROKORWAS_PPNS','BAGWASSIDIK','Bagian Pengawasan Penyidikan','BAGIAN',10),('BARESKRIM','ROKORWAS_PPNS','BAGBIN_PPNS','Bagian Pembinaan PPNS','BAGIAN',20),('BARESKRIM','ROKORWAS_PPNS','BAGBANOPS','Bagian Bantuan Operasi','BAGIAN',30),('BARESKRIM','ROKORWAS_PPNS','BAGMINPERS_PPNS','Bagian Administrasi Personel PPNS','BAGIAN',40),('BARESKRIM','ROKORWAS_PPNS','URTU','Urusan Tata Usaha','URUSAN',50),
 ('BARESKRIM','PUSIKNAS','SET','Sekretariat','SEKRETARIAT',10),('BARESKRIM','PUSIKNAS','URKEU','Urusan Keuangan','URUSAN',20),('BARESKRIM','PUSIKNAS','BIDBANGSIS','Bidang Pengembangan Sistem','BIDANG',30),('BARESKRIM','PUSIKNAS','BIDYANINFOKRIM','Bidang Pelayanan Informasi Kriminal','BIDANG',40),('BARESKRIM','PUSIKNAS','BIDKERMA','Bidang Kerja Sama','BIDANG',50),('BARESKRIM','PUSIKNAS','BIDPDAKT','Bidang Pusat Data dan Analisis Kejahatan Transnasional','BIDANG',60),
 ('BARESKRIM','PUSIDENT','SET','Sekretariat','SEKRETARIAT',10),('BARESKRIM','PUSIDENT','BAGSISINFO','Bagian Sistem Informasi','BAGIAN',20),('BARESKRIM','PUSIDENT','URKEU','Urusan Keuangan','URUSAN',30),('BARESKRIM','PUSIDENT','BIDDAKTIUM','Bidang Daktiloskopi Umum','BIDANG',40),('BARESKRIM','PUSIDENT','BIDDAKTIKRIM','Bidang Daktiloskopi Kriminal','BIDANG',50),('BARESKRIM','PUSIDENT','BIDTOPOL','Bidang Fotografi Kepolisian','BIDANG',60),
 ('BARESKRIM','PUSLABFOR','SET','Sekretariat','SEKRETARIAT',10),('BARESKRIM','PUSLABFOR','BAGJEMENMUT','Bagian Manajemen Mutu','BAGIAN',20),('BARESKRIM','PUSLABFOR','URKEU','Urusan Keuangan','URUSAN',30),('BARESKRIM','PUSLABFOR','BIDDOKUPALFOR','Bidang Dokumen dan Uang Palsu Forensik','BIDANG',40),('BARESKRIM','PUSLABFOR','BIDBALMETFOR','Bidang Balistik Metalurgi Forensik','BIDANG',50),('BARESKRIM','PUSLABFOR','BIDFISKOMFOR','Bidang Fisika Komputer Forensik','BIDANG',60),('BARESKRIM','PUSLABFOR','BIDKIMBIOFOR','Bidang Kimia Biologi Forensik','BIDANG',70),('BARESKRIM','PUSLABFOR','BIDNARKOBAFOR','Bidang Narkoba Forensik','BIDANG',80),
 ('ITWASUM','RORENMIN','BAGRENDAFUNG','Bagian Perencanaan, Sumber Daya dan Pembinaan Fungsi','BAGIAN',10),('ITWASUM','RORENMIN','BAGANEV','Bagian Analisis dan Evaluasi','BAGIAN',20),('ITWASUM','RORENMIN','BAGDUMAS','Bagian Pengaduan Masyarakat','BAGIAN',30),('ITWASUM','RORENMIN','BAGDALMUTU','Bagian Pengendalian Mutu','BAGIAN',40),('ITWASUM','RORENMIN','URTU','Urusan Tata Usaha','URUSAN',50),
 ('ITWASUM','ITWIL_1','ITBID','Inspektorat Bidang','BIDANG',10),('ITWASUM','ITWIL_1','AUDITOR','Auditor','UNIT',20),('ITWASUM','ITWIL_1','URTU','Urusan Tata Usaha','URUSAN',30),('ITWASUM','ITWIL_2','ITBID','Inspektorat Bidang','BIDANG',10),('ITWASUM','ITWIL_2','AUDITOR','Auditor','UNIT',20),('ITWASUM','ITWIL_2','URTU','Urusan Tata Usaha','URUSAN',30),('ITWASUM','ITWIL_3','ITBID','Inspektorat Bidang','BIDANG',10),('ITWASUM','ITWIL_3','AUDITOR','Auditor','UNIT',20),('ITWASUM','ITWIL_3','URTU','Urusan Tata Usaha','URUSAN',30),('ITWASUM','ITWIL_4','ITBID','Inspektorat Bidang','BIDANG',10),('ITWASUM','ITWIL_4','AUDITOR','Auditor','UNIT',20),('ITWASUM','ITWIL_4','URTU','Urusan Tata Usaha','URUSAN',30),('ITWASUM','ITWIL_5','ITBID','Inspektorat Bidang','BIDANG',10),('ITWASUM','ITWIL_5','AUDITOR','Auditor','UNIT',20),('ITWASUM','ITWIL_5','URTU','Urusan Tata Usaha','URUSAN',30)
), targets AS (SELECT id_satker,kode_satker FROM satker WHERE tipe_satker IN ('SATKER_MABES'))
INSERT INTO unit_kerja(id_unit,kode_unit,nama_unit,id_satker,tipe_unit,id_unit_induk,sumber_sotk,versi_sotk,is_placeholder,is_active)
SELECT COALESCE((SELECT MAX(id_unit) FROM unit_kerja)+ROW_NUMBER() OVER (ORDER BY t.id_satker,n.urutan),0),n.parent_code || '_' || n.kode,n.nama,t.id_satker,n.tipe,p.id_unit,'Perkap No. 6 Tahun 2017 / Perpol No. 4 Tahun 2025','2017/2025',FALSE,TRUE
FROM targets t JOIN nodes n ON n.satker_code=t.kode_satker JOIN unit_kerja p ON p.id_satker=t.id_satker AND p.kode_unit=n.parent_code
ON CONFLICT(id_satker,kode_unit) DO UPDATE SET nama_unit=EXCLUDED.nama_unit,tipe_unit=EXCLUDED.tipe_unit,id_unit_induk=EXCLUDED.id_unit_induk,sumber_sotk=EXCLUDED.sumber_sotk,versi_sotk=EXCLUDED.versi_sotk,is_placeholder=FALSE,is_active=TRUE;
INSERT INTO fungsi(kode_fungsi,nama_fungsi,is_active) SELECT LEFT('SATFUNG_'||kode_unit,30),MIN(nama_unit),TRUE FROM unit_kerja WHERE id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT is_placeholder GROUP BY kode_unit ON CONFLICT(kode_fungsi) DO UPDATE SET nama_fungsi=EXCLUDED.nama_fungsi,is_active=TRUE;
INSERT INTO satker_fungsi(id_satker,id_fungsi,is_active) SELECT u.id_satker,f.id_fungsi,TRUE FROM unit_kerja u JOIN fungsi f ON f.kode_fungsi=LEFT('SATFUNG_'||u.kode_unit,30) WHERE u.id_satker IN (SELECT id_satker FROM satker WHERE tipe_satker='SATKER_MABES') AND NOT u.is_placeholder ON CONFLICT(id_satker,id_fungsi) DO UPDATE SET is_active=TRUE,updated_at=NOW();
COMMIT;
