-- Migration 016: penilaian merit berbasis periode, indikator, dan bukti.
-- Bobot disimpan di database agar dapat diubah melalui kebijakan/versioning,
-- bukan di-hard-code pada frontend.
BEGIN;

CREATE TABLE IF NOT EXISTS merit_period (
  id_period INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_period VARCHAR(40) NOT NULL UNIQUE,
  nama_period VARCHAR(120) NOT NULL,
  tanggal_mulai DATE NOT NULL,
  tanggal_selesai DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','AKTIF','DITUTUP')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (tanggal_selesai >= tanggal_mulai)
);

CREATE TABLE IF NOT EXISTS merit_indicator (
  id_indicator INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_indicator VARCHAR(40) NOT NULL UNIQUE,
  nama_indicator VARCHAR(120) NOT NULL,
  deskripsi TEXT NOT NULL,
  bobot NUMERIC(5,2) NOT NULL CHECK (bobot >= 0 AND bobot <= 100),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS merit_assessment (
  id_assessment BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pegawai INTEGER NOT NULL REFERENCES pegawai(id_pegawai) ON DELETE CASCADE,
  id_period INTEGER NOT NULL REFERENCES merit_period(id_period),
  id_indicator INTEGER NOT NULL REFERENCES merit_indicator(id_indicator),
  nilai_raw NUMERIC(5,2) NOT NULL CHECK (nilai_raw >= 0 AND nilai_raw <= 100),
  bukti TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','DIAJUKAN','DIVERIFIKASI','DITOLAK')),
  assessed_by INTEGER REFERENCES users(id_user),
  verified_by INTEGER REFERENCES users(id_user),
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id_pegawai, id_period, id_indicator)
);

CREATE INDEX IF NOT EXISTS ix_merit_assessment_person_period ON merit_assessment(id_pegawai, id_period);
CREATE INDEX IF NOT EXISTS ix_merit_assessment_status ON merit_assessment(status);

-- Hak minimum untuk role runtime aplikasi; DDL tetap dijalankan administrator.
GRANT SELECT ON merit_period, merit_indicator, merit_assessment TO user_personel;
GRANT INSERT, UPDATE, DELETE ON merit_assessment TO user_personel;
GRANT USAGE, SELECT ON SEQUENCE merit_period_id_period_seq, merit_indicator_id_indicator_seq, merit_assessment_id_assessment_seq TO user_personel;

COMMIT;
