-- Migration 017: kualifikasi pendidikan dan riwayat diklat personel.
-- Tabel additive agar sumber staging lama tidak diubah atau dihapus.
BEGIN;

CREATE TABLE IF NOT EXISTS riwayat_pendidikan_personel (
  id_pendidikan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pegawai INTEGER NOT NULL REFERENCES pegawai(id_pegawai) ON DELETE CASCADE,
  jenjang VARCHAR(5) NOT NULL CHECK (jenjang IN ('SD','SMP','SMA','D1','D2','D3','D4','S1','S2','S3')),
  institusi VARCHAR(150) NOT NULL,
  jurusan VARCHAR(150),
  tahun_lulus SMALLINT CHECK (tahun_lulus IS NULL OR tahun_lulus BETWEEN 1900 AND 2100),
  nomor_ijazah VARCHAR(100),
  keterangan TEXT,
  created_by INTEGER REFERENCES users(id_user),
  updated_by INTEGER REFERENCES users(id_user),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS riwayat_diklat_personel (
  id_diklat BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pegawai INTEGER NOT NULL REFERENCES pegawai(id_pegawai) ON DELETE CASCADE,
  nama_diklat VARCHAR(200) NOT NULL,
  jenis_diklat VARCHAR(100),
  penyelenggara VARCHAR(150),
  tanggal_mulai DATE,
  tanggal_selesai DATE,
  jam_pelajaran INTEGER CHECK (jam_pelajaran IS NULL OR jam_pelajaran BETWEEN 0 AND 10000),
  nilai NUMERIC(5,2) CHECK (nilai IS NULL OR nilai BETWEEN 0 AND 100),
  nomor_sertifikat VARCHAR(100),
  keterangan TEXT,
  created_by INTEGER REFERENCES users(id_user),
  updated_by INTEGER REFERENCES users(id_user),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (tanggal_selesai IS NULL OR tanggal_mulai IS NULL OR tanggal_selesai >= tanggal_mulai)
);

CREATE INDEX IF NOT EXISTS ix_pendidikan_personel ON riwayat_pendidikan_personel(id_pegawai, tahun_lulus DESC);
CREATE INDEX IF NOT EXISTS ix_diklat_personel ON riwayat_diklat_personel(id_pegawai, tanggal_mulai DESC);

GRANT SELECT ON riwayat_pendidikan_personel, riwayat_diklat_personel TO user_personel;
GRANT INSERT, UPDATE, DELETE ON riwayat_pendidikan_personel, riwayat_diklat_personel TO user_personel;
GRANT USAGE, SELECT ON SEQUENCE riwayat_pendidikan_personel_id_pendidikan_seq, riwayat_diklat_personel_id_diklat_seq TO user_personel;

COMMIT;
