-- Migration 038: backfill data legacy ke domain riwayat personel.
-- Sumber legacy tidak dihapus/diubah. Baris yang sudah memiliki padanan domain
-- tidak disalin ulang agar migrasi aman dijalankan lebih dari sekali.

BEGIN;

CREATE TABLE IF NOT EXISTS riwayat_mutasi_personel (
  id_mutasi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pegawai INTEGER NOT NULL REFERENCES pegawai (id_pegawai) ON DELETE CASCADE,
  id_unit_lama INTEGER REFERENCES unit_kerja (id_unit),
  id_unit_baru INTEGER NOT NULL REFERENCES unit_kerja (id_unit),
  nomor_sk VARCHAR(50),
  tanggal_sk DATE,
  tmt_mutasi DATE NOT NULL,
  sumber_data VARCHAR(20) NOT NULL DEFAULT 'domain',
  created_by INTEGER REFERENCES users (id_user),
  updated_by INTEGER REFERENCES users (id_user),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_riwayat_mutasi_personel_sumber CHECK (sumber_data IN ('domain', 'legacy'))
);

CREATE INDEX IF NOT EXISTS ix_mutasi_personel_pegawai_waktu
  ON riwayat_mutasi_personel (id_pegawai, tmt_mutasi DESC);

INSERT INTO riwayat_pendidikan_personel
  (id_pegawai, jenjang, institusi, jurusan, tahun_lulus, created_at, updated_at)
SELECT DISTINCT l.id_pegawai, UPPER(TRIM(l.jenjang)), TRIM(l.institusi), NULLIF(TRIM(l.jurusan), ''), l.tahun_lulus, NOW(), NOW()
FROM riwayat_pendidikan l
WHERE NOT EXISTS (
  SELECT 1
  FROM riwayat_pendidikan_personel d
  WHERE d.id_pegawai = l.id_pegawai
    AND UPPER(TRIM(d.jenjang)) IS NOT DISTINCT FROM UPPER(TRIM(l.jenjang))
    AND d.institusi IS NOT DISTINCT FROM TRIM(l.institusi)
    AND d.jurusan IS NOT DISTINCT FROM NULLIF(TRIM(l.jurusan), '')
    AND d.tahun_lulus IS NOT DISTINCT FROM l.tahun_lulus
);

INSERT INTO riwayat_diklat_personel
  (id_pegawai, nama_diklat, penyelenggara, tanggal_mulai, tanggal_selesai, jam_pelajaran, nilai, created_at, updated_at)
SELECT DISTINCT l.id_pegawai, TRIM(d.nama_diklat), NULLIF(TRIM(d.penyelenggara), ''), l.tanggal_mulai, l.tanggal_selesai, d.jam_pelajaran, l.nilai, NOW(), NOW()
FROM riwayat_diklat l
JOIN diklat d ON d.id_diklat = l.id_diklat
WHERE NOT EXISTS (
  SELECT 1
  FROM riwayat_diklat_personel p
  WHERE p.id_pegawai = l.id_pegawai
    AND p.nama_diklat IS NOT DISTINCT FROM TRIM(d.nama_diklat)
    AND p.penyelenggara IS NOT DISTINCT FROM NULLIF(TRIM(d.penyelenggara), '')
    AND p.tanggal_mulai IS NOT DISTINCT FROM l.tanggal_mulai
    AND p.tanggal_selesai IS NOT DISTINCT FROM l.tanggal_selesai
    AND p.nilai IS NOT DISTINCT FROM l.nilai
);

INSERT INTO riwayat_mutasi_personel
  (id_pegawai, id_unit_lama, id_unit_baru, nomor_sk, tanggal_sk, tmt_mutasi, sumber_data, created_at, updated_at)
SELECT DISTINCT l.id_pegawai, l.id_unit_lama, l.id_unit_baru, l.nomor_sk, l.tanggal_sk, l.tmt_mutasi, 'legacy', NOW(), NOW()
FROM riwayat_mutasi l
WHERE NOT EXISTS (
  SELECT 1
  FROM riwayat_mutasi_personel d
  WHERE d.id_pegawai = l.id_pegawai
    AND d.id_unit_lama IS NOT DISTINCT FROM l.id_unit_lama
    AND d.id_unit_baru = l.id_unit_baru
    AND d.nomor_sk IS NOT DISTINCT FROM l.nomor_sk
    AND d.tanggal_sk IS NOT DISTINCT FROM l.tanggal_sk
    AND d.tmt_mutasi = l.tmt_mutasi
);

GRANT SELECT ON riwayat_mutasi_personel TO user_personel;
GRANT USAGE, SELECT ON SEQUENCE riwayat_mutasi_personel_id_mutasi_seq TO user_personel;

COMMIT;
